### ISSUE TITLE
How do I remove milliseconds from a script?

### ISSUE THREAD

**Issue by AdventurerRussia** [Arieleg/mpv-copyTime#1]
Hello, please help me remove milliseconds from the script. I don't need them in my work, but they take time to delete.

**Comment by Arieleg** [comment]
Hello, sorry to respond so long after. You need to change the strig format. 
For lua script:
Replace: time = string.format("%02d:%02d:%02d.%s", time_hours, time_minutes, time_seg, time_ms)
With: time = string.format("%02d:%02d:%02d", time_hours, time_minutes, time_seg)
