### ISSUE TITLE
How can set up this function in GNU/Linux?

### ISSUE THREAD

**Issue by Villelmo** [Arieleg/mpv-copyTime#3]
I try to do follow the instructions but i don't get any result. The command [Ctrl + Alt + C] it's not functional in my operating system. 

I install PowerShell on Linux. 

Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Comment by Villelmo** [comment]
I install PowerShell on Linux

**Comment by Arieleg** [comment]
Hi, for Set-Clipboard to work on Linux, you must have xclip installed. I recommend you to use the xclip version, check the readme file, I just updated it. I hope it helps you.

**Comment by Villelmo** [comment]
I have installed xclip 0.13. Copy the current time of the video to clipboard but don't paste it in a text editor. 

```
lua: copyTime-xclip.lua:1: module 'mp' not found:
	no field package.preload['mp']
	no file '/usr/local/share/lua/5.3/mp.lua'
	no file '/usr/local/share/lua/5.3/mp/init.lua'
	no file '/usr/local/lib/lua/5.3/mp.lua'
	no file '/usr/local/lib/lua/5.3/mp/init.lua'
	no file '/usr/share/lua/5.3/mp.lua'
	no file '/usr/share/lua/5.3/mp/init.lua'
	no file './mp.lua'
	no file './mp/init.lua'
	no file '/usr/local/lib/lua/5.3/mp.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/mp.so'
	no file '/usr/lib/lua/5.3/mp.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './mp.so'
stack traceback:
	[C]: in function 'require'
	copyTime-xclip.lua:1: in main chunk
	[C]: in ?

```

**Comment by Arieleg** [comment]
Hello, did you follow the instructions? https://github.com/Arieleg/mpv-copyTime#gnulinux
That message where did you get it from?

**Comment by Villelmo** [comment]
Yeah!. I compile the script _copyTime-xclip.lua_ and get this message.

**Comment by Arieleg** [comment]
It is a script that does not need to be compiled. mpv provides the built-in mp module, that's why you get that message.
Did you give copyTime-xclip.sh execute permissions?
chmod +x copyTime-xclip.sh

**Comment by Villelmo** [comment]
**00:00:09.968**
Ready!

Thanks.

**Comment by Arieleg** [comment]
great! you're welcome.
