### ISSUE TITLE
Windows CTRL + C exit MPV Player instead of copying time.

### ISSUE THREAD

**Issue by anonymoustly444** [Arieleg/mpv-copyTime#5]

**Comment by anonymoustly444** [comment]
Exist on Windows 8.1 (not sure if this is Windows version related)

**Comment by Arieleg** [comment]
Hello, yes, that is the default behavior (exit by pressing Ctrl + c). It may be that the script is not installed correctly or there is a conflict with the bindings. You can try edit the last line of the script (line 21 in copyTime.lua) to change the binding (for example, Shift + Ctrl + c). Greetings.
